version: "3.8"
services:
    db:
        image: mysql:5.7
        environment: 
            - MYSQL_DATABASE=drupal
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
    drupal:
        build: ./drupal
        